### PR TITLE
Remove usage of hard deprecated function wfIsBadImage()

### PR DESCRIPTION
**Pull request by supertassu**
Refs: https://phabricator.wikimedia.org/T249459 which affects MW 1.35.x

### CODE REVIEW

**Comment by kghbln** [comment]
@oetterer If you could have a peep at this. :)

**Comment by oetterer** [comment]
Have to set up my new Workstation this week. Then I will check it out. Thanks @kghbln and @supertassu .

**Comment by Seb35** [comment]
The service BadFileLookup does not exist before MediaWiki 1.34, so this patch (necessary on 1.36+) breaks de facto the compatibility 1.33- on this code path.

**Comment by Seb35** [comment]
I prepared a backward-compatible version of this patch, it is available in #29 (I cannot push into this Pull Request).

**Comment by oetterer** [comment]
resolved by #29

**Pull request closed without merging**
